#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
killall -9 picom sxhkd dunst xfce4-power-manager
sxhkd &
#nm-applet &
$HOME/.config/polybar/material/launch.sh
#feh --bg-fill /usr/share/backgrounds/bspwm/wall.png
/usr/lib/polkit-kde-authentication-agent-1 &

while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
#picom -b --experimental-backends --config $HOME/.config/bspwm/picom.conf &
picom &
nitrogen --restore &
dunst -config $HOME/.config/dunst/dunstrc &
xfce4-power-manager &
bspc monitor -d I II III IV V
#bspc monitor -d HDMI2 VI


bspc config border_width         3
bspc config window_gap           5
bspc config border_radius 		 10			# And install yay -S picom-pijulius-git
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^2' state=floating follow=on
bspc rule -a firefox desktop='^3'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


